# _config.yml

theme: minima

plugins:
  - jekyll-last-modified-at
  - jekyll-timeago

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%b %d, %Y' # outputs > Jan 01, 2023
